meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: logstash-syslog
    templates:
    - name: logstash-syslog
      release: logstash
    instances: 1
    persistent_disk: 0
    resource_pool: small_z1
    networks: (( merge ))

  - name: logstash-indexer
    templates:
    - name: logstash-indexer
      release: logstash
    instances: 1
    persistent_disk: 0
    resource_pool: small_z1
    networks: (( merge ))

networks: (( merge ))

properties: {}
